version: "3.8"
services:
  frontend:
    build: ./frontend
    ports:
      - 5173:5173
  backend:
    build: ./backend
    ports:
      - 8080:8080
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    depends_on:
      - db
  db:
    image: postgres:16.2-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_PASSWORD}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: chatapp
    volumes:
      - mentormedb:/var/lib/postgresql/data

volumes:
  mentormedb: {}